apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-helm-poc
spec:
  selector:
    matchLabels:
      app: k8s-helm-poc
  replicas: 4
  template:
    metadata:
      labels:
        app: k8s-helm-poc
    spec:
      containers:
        - name: k8s-helm-poc
          image: {{ .Values.image.repository }}:{{ .Values.appVersion }}
          ports:
            - containerPort: 8888
              protocol: TCP