kind: Service
apiVersion: v1
metadata:
  name: k8s-helm-poc
spec:
  type: NodePort
  selector:
    app: k8s-helm-poc
  ports:
  - nodePort: 31000
    port: 8888
    targetPort: 8888
    name: http
    protocol: TCP